"""基础数据常量：港口、承运商、航线。

数据与执行逻辑分离，便于校对和扩充。
航线（ROUTES）不入库：9 张核心表里没有 routes 表，
航线是"起点港口 + 终点港口 + 运输方式"的组合，供模拟器生成 legs 时消费。
"""

# 全球主要港口（覆盖中国、东南亚、欧洲、北美、南美、中东、非洲、大洋洲）
PORTS: list[dict] = [
    {
        "code": "CNSHA",
        "name": "上海港",
        "type": "port",
        "lat": 31.2304,
        "lng": 121.4737,
        "country": "中国",
    },
    {
        "code": "CNNGB",
        "name": "宁波舟山港",
        "type": "port",
        "lat": 29.8683,
        "lng": 121.5440,
        "country": "中国",
    },
    {
        "code": "CNSZX",
        "name": "深圳港",
        "type": "port",
        "lat": 22.5431,
        "lng": 114.0579,
        "country": "中国",
    },
    {
        "code": "CNTAO",
        "name": "青岛港",
        "type": "port",
        "lat": 36.0671,
        "lng": 120.3826,
        "country": "中国",
    },
    {
        "code": "CNTJN",
        "name": "天津港",
        "type": "port",
        "lat": 38.7223,
        "lng": 117.2010,
        "country": "中国",
    },
    {
        "code": "CNXMN",
        "name": "厦门港",
        "type": "port",
        "lat": 24.4798,
        "lng": 118.0894,
        "country": "中国",
    },
    {
        "code": "HKHKG",
        "name": "香港港",
        "type": "port",
        "lat": 22.3193,
        "lng": 114.1694,
        "country": "中国香港",
    },
    {
        "code": "SGSIN",
        "name": "新加坡港",
        "type": "port",
        "lat": 1.2644,
        "lng": 103.8400,
        "country": "新加坡",
    },
    {
        "code": "KRPUS",
        "name": "釜山港",
        "type": "port",
        "lat": 35.1019,
        "lng": 129.0300,
        "country": "韩国",
    },
    {
        "code": "JPTYO",
        "name": "东京港",
        "type": "port",
        "lat": 35.5494,
        "lng": 139.7798,
        "country": "日本",
    },
    {
        "code": "MYPKG",
        "name": "巴生港",
        "type": "port",
        "lat": 3.0000,
        "lng": 101.4000,
        "country": "马来西亚",
    },
    {
        "code": "VNSGN",
        "name": "胡志明港",
        "type": "port",
        "lat": 10.7769,
        "lng": 106.7009,
        "country": "越南",
    },
    {
        "code": "THLCH",
        "name": "林查班港",
        "type": "port",
        "lat": 13.0830,
        "lng": 100.8830,
        "country": "泰国",
    },
    {
        "code": "INNSA",
        "name": "那瓦西瓦港",
        "type": "port",
        "lat": 18.9500,
        "lng": 72.9500,
        "country": "印度",
    },
    {
        "code": "AEJEA",
        "name": "杰贝阿里港",
        "type": "port",
        "lat": 25.0159,
        "lng": 55.0616,
        "country": "阿联酋",
    },
    {
        "code": "EGPDT",
        "name": "塞得港",
        "type": "port",
        "lat": 31.2653,
        "lng": 32.3019,
        "country": "埃及",
    },
    {
        "code": "TRIST",
        "name": "伊斯坦布尔港",
        "type": "port",
        "lat": 41.0151,
        "lng": 28.9795,
        "country": "土耳其",
    },
    {
        "code": "NLRTM",
        "name": "鹿特丹港",
        "type": "port",
        "lat": 51.9496,
        "lng": 4.1453,
        "country": "荷兰",
    },
    {
        "code": "DEHAM",
        "name": "汉堡港",
        "type": "port",
        "lat": 53.5461,
        "lng": 9.9661,
        "country": "德国",
    },
    {
        "code": "BEANR",
        "name": "安特卫普港",
        "type": "port",
        "lat": 51.2600,
        "lng": 4.4000,
        "country": "比利时",
    },
    {
        "code": "GBFXT",
        "name": "费利克斯托港",
        "type": "port",
        "lat": 51.9630,
        "lng": 1.3510,
        "country": "英国",
    },
    {
        "code": "ESVLC",
        "name": "瓦伦西亚港",
        "type": "port",
        "lat": 39.4699,
        "lng": -0.3763,
        "country": "西班牙",
    },
    {
        "code": "USLAX",
        "name": "洛杉矶港",
        "type": "port",
        "lat": 33.7395,
        "lng": -118.2610,
        "country": "美国",
    },
    {
        "code": "USNYC",
        "name": "纽约港",
        "type": "port",
        "lat": 40.6635,
        "lng": -74.0937,
        "country": "美国",
    },
    {
        "code": "BRSSZ",
        "name": "桑托斯港",
        "type": "port",
        "lat": -23.9608,
        "lng": -46.3336,
        "country": "巴西",
    },
    {
        "code": "ZADUR",
        "name": "德班港",
        "type": "port",
        "lat": -29.8700,
        "lng": 31.0300,
        "country": "南非",
    },
    {
        "code": "AUSYD",
        "name": "悉尼港",
        "type": "port",
        "lat": -33.8568,
        "lng": 151.2153,
        "country": "澳大利亚",
    },
]

# 承运商：海运为主，空运 / 铁路 / 陆运各备几家（avg_speed 单位 km/h）
CARRIERS: list[dict] = [
    {"name": "Maersk 马士基", "mode": "sea", "avg_speed": 35.0},
    {"name": "COSCO 中远海运", "mode": "sea", "avg_speed": 33.0},
    {"name": "CMA CGM 达飞", "mode": "sea", "avg_speed": 34.0},
    {"name": "MSC 地中海航运", "mode": "sea", "avg_speed": 34.0},
    {"name": "Hapag-Lloyd 赫伯罗特", "mode": "sea", "avg_speed": 33.0},
    {"name": "ONE 海洋网联船务", "mode": "sea", "avg_speed": 32.0},
    {"name": "Evergreen 长荣海运", "mode": "sea", "avg_speed": 33.0},
    {"name": "Cathay Cargo 国泰货运", "mode": "air", "avg_speed": 800.0},
    {"name": "China Cargo 中货航", "mode": "air", "avg_speed": 780.0},
    {"name": "FedEx 联邦快递", "mode": "air", "avg_speed": 820.0},
    {"name": "CR Express 中欧班列", "mode": "rail", "avg_speed": 60.0},
    {"name": "RZD 俄铁", "mode": "rail", "avg_speed": 55.0},
    {"name": "DBL 德邦物流", "mode": "road", "avg_speed": 55.0},
]

# 典型航线（OD 对）：供模拟器生成 legs 使用
ROUTES: list[dict] = [
    {"origin": "CNSHA", "dest": "NLRTM", "mode": "sea"},
    {"origin": "CNNGB", "dest": "USLAX", "mode": "sea"},
    {"origin": "CNSZX", "dest": "DEHAM", "mode": "sea"},
    {"origin": "SGSIN", "dest": "AEJEA", "mode": "sea"},
    {"origin": "KRPUS", "dest": "USLAX", "mode": "sea"},
    {"origin": "CNTJN", "dest": "USNYC", "mode": "sea"},
    {"origin": "HKHKG", "dest": "GBFXT", "mode": "sea"},
    {"origin": "CNSHA", "dest": "AUSYD", "mode": "sea"},
    {"origin": "CNTAO", "dest": "BRSSZ", "mode": "sea"},
    {"origin": "CNSZX", "dest": "VNSGN", "mode": "sea"},
    {"origin": "MYPKG", "dest": "ZADUR", "mode": "sea"},
    {"origin": "HKHKG", "dest": "NLRTM", "mode": "air"},
    {"origin": "CNTAO", "dest": "DEHAM", "mode": "rail"},
]
