"""init schema

Revision ID: 8420f0d71c49
Revises: 7e7c897d30ad
Create Date: 2026-09-07 22:54:03.442665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8420f0d71c49'
down_revision: Union[str, None] = '7e7c897d30ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.Enum('sea', 'road', 'air', 'rail', name='carrier_mode'), nullable=False),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('port', 'warehouse', 'city', name='location_type'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_transit', 'delivered', 'delayed', name='shipment_status'), server_default='planned', nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('planned_departure', sa.DateTime(), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(), nullable=True),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('latest_lat', sa.Float(), nullable=True),
    sa.Column('latest_lng', sa.Float(), nullable=True),
    sa.Column('latest_ts', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['dest_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_no')
    )
    op.create_index('idx_shipments_order', 'shipments', ['order_id'], unique=False)
    op.create_index('idx_shipments_status', 'shipments', ['status'], unique=False)
    op.create_table('exception_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('delay', 'stalled', 'route_deviation', name='exception_type'), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'critical', name='exception_level'), server_default='info', nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exceptions_shipment', 'exception_records', ['shipment_id', 'detected_at'], unique=False)
    op.create_table('legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('sea', 'road', 'air', 'rail', name='leg_mode'), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'skipped', name='leg_status'), server_default='planned', nullable=False),
    sa.ForeignKeyConstraint(['dest_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_legs_shipment', 'legs', ['shipment_id'], unique=False)
    op.create_table('milestone_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('picked_up', 'loaded', 'departed', 'arrived', 'delivered', 'delayed', 'stalled', name='milestone_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_shipment_time', 'milestone_events', ['shipment_id', 'occurred_at'], unique=False)
    op.create_table('position_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    op.create_index('idx_leg_time', 'position_points', ['leg_id', 'recorded_at'], unique=False)
    # MySQL 按月分区：autogenerate 不生成，需手写
    # recorded_at 已在主键里（MySQL 要求分区键必须属于所有唯一键）
    op.execute(
        "ALTER TABLE position_points "
        "PARTITION BY RANGE (TO_DAYS(recorded_at)) ("
        "PARTITION p_init VALUES LESS THAN MAXVALUE)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leg_time', table_name='position_points')
    op.drop_table('position_points')
    op.drop_index('idx_events_shipment_time', table_name='milestone_events')
    op.drop_table('milestone_events')
    op.drop_index('idx_legs_shipment', table_name='legs')
    op.drop_table('legs')
    op.drop_index('idx_exceptions_shipment', table_name='exception_records')
    op.drop_table('exception_records')
    op.drop_index('idx_shipments_status', table_name='shipments')
    op.drop_index('idx_shipments_order', table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_table('locations')
    op.drop_table('carriers')
    # ### end Alembic commands ###
